<section id="how-it-works" class="border-y border-ringside-signal-border bg-gradient-to-br from-ringside-red to-ringside-red-dark py-[clamp(4.25rem,6vw,6rem)] text-ringside-white max-[767px]:py-14" aria-labelledby="show-title">
    <x-page-width>
        <x-section-heading id="show-title" heading="Plan the night. Preserve the story." description="Ringside follows the sequence promoters already know. Set the stage, build the card, run the night and carry the story forward." />
        <div class="mt-14 grid grid-cols-2 gap-12 max-[767px]:mt-10 max-[767px]:grid-cols-1 max-[767px]:gap-8">
            <div id="events" class="border-t border-ringside-white-half pt-8 max-[767px]:pt-5"><span class="mb-8 block text-xs font-bold uppercase tracking-[0.1em] text-ringside-signal-soft max-[767px]:mb-5">Before the bell</span><svg class="mb-8 h-10 w-10 stroke-current stroke-[1.5] max-[767px]:mb-5 max-[767px]:h-8 max-[767px]:w-8" viewBox="0 0 24 24" aria-hidden="true"><circle cx="12" cy="12" r="9"/><path d="M12 7v5l3 2"/></svg><x-display-heading tag="h3" class="mb-4 text-[clamp(2rem,3.5vw,3rem)] max-[767px]:mb-3">Set the stage.</x-display-heading><p class="text-[1.125rem] leading-[1.75] max-[767px]:text-base max-[767px]:leading-[1.6]">Organize events around your venues and dates. Keep the details of each show together as the card takes shape.</p><p class="mt-6 text-sm font-bold max-[767px]:mt-4">Events / Venues / Scheduling</p></div>
            <div id="matches" class="border-t border-ringside-white-half pt-8 max-[767px]:pt-5"><span class="mb-8 block text-xs font-bold uppercase tracking-[0.1em] text-ringside-signal-soft max-[767px]:mb-5">When the card is set</span><svg class="mb-8 h-10 w-10 stroke-current stroke-[1.5] max-[767px]:mb-5 max-[767px]:h-8 max-[767px]:w-8" viewBox="0 0 24 24" aria-hidden="true"><rect x="4" y="3" width="16" height="18" rx="1"/><path d="M8 7h8M8 11h8M8 15h5"/></svg><x-display-heading tag="h3" class="mb-4 text-[clamp(2rem,3.5vw,3rem)] max-[767px]:mb-3">Build the card.</x-display-heading><p class="text-[1.125rem] leading-[1.75] max-[767px]:text-base max-[767px]:leading-[1.6]">Book wrestlers and tag teams, choose match types and assign officials. Record results when the match is done.</p><p class="mt-6 text-sm font-bold max-[767px]:mt-4">Competitors / Match types / Results</p></div>
        </div>
        <div class="mt-[4.5rem] grid grid-cols-4 gap-4 border-t border-ringside-white-half max-[767px]:mt-10 max-[767px]:grid-cols-1">
            <x-workflow-step number="01" title="Create your promotion">Create an account and open your Ringside workspace.</x-workflow-step>
            <x-workflow-step number="02" title="Build your roster">Add your wrestlers, teams, stables, managers and referees.</x-workflow-step>
            <x-workflow-step number="03" title="Book your show">Create an event, build the card and assign the people behind it.</x-workflow-step>
            <x-workflow-step number="04" title="Run the business">Record results and keep your promotion’s history moving forward.</x-workflow-step>
        </div>
    </x-page-width>
</section>
