<section id="how-it-works" class="relative isolate overflow-hidden border-y border-ringside-signal-border bg-ringside-red-dark py-[clamp(4.25rem,6vw,6rem)] text-ringside-white max-[767px]:py-14" aria-labelledby="show-title">
    <img class="absolute inset-0 -z-10 h-full w-full object-cover object-[center_52%] max-[767px]:object-[70%_50%]" src="images/marketing/show-planning.webp" width="1672" height="941" alt="" aria-hidden="true" loading="lazy">
    <div class="absolute inset-0 -z-10 bg-[linear-gradient(90deg,rgb(166_25_32_/_84%)_0%,rgb(166_25_32_/_76%)_48%,rgb(166_25_32_/_58%)_100%)] max-[767px]:bg-[linear-gradient(180deg,rgb(166_25_32_/_58%)_0%,rgb(166_25_32_/_64%)_100%)]" aria-hidden="true"></div>
    <x-page-width class="relative">
        <x-section-heading id="show-title" heading="Build the card before the bell." description="Set the venue and date, then bring the right people, officials and title into one match card." />
        <div class="mt-14 grid grid-cols-2 gap-12 max-[767px]:mt-10 max-[767px]:grid-cols-1 max-[767px]:gap-8">
            <div id="events" class="border-t border-ringside-white-half pt-8 max-[767px]:pt-5"><span class="mb-8 block text-xs font-bold uppercase tracking-[0.1em] text-ringside-white max-[767px]:mb-5">Set the stage</span><svg class="mb-8 h-10 w-10 stroke-current stroke-[1.5] max-[767px]:mb-5 max-[767px]:h-8 max-[767px]:w-8" viewBox="0 0 24 24" aria-hidden="true"><circle cx="12" cy="12" r="9"/><path d="M12 7v5l3 2"/></svg><x-display-heading tag="h3" class="mb-4 text-[clamp(2rem,3.5vw,3rem)] max-[767px]:mb-3">Start with the event.</x-display-heading><p class="text-[1.125rem] leading-[1.75] max-[767px]:text-base max-[767px]:leading-[1.6]">Keep the venue, date and show details together as the night takes shape.</p><p class="mt-6 text-sm font-bold max-[767px]:mt-4">Events / Venues / Scheduling</p></div>
            <div id="matches" class="border-t border-ringside-white-half pt-8 max-[767px]:pt-5"><span class="mb-8 block text-xs font-bold uppercase tracking-[0.1em] text-ringside-white max-[767px]:mb-5">Before the bell</span><svg class="mb-8 h-10 w-10 stroke-current stroke-[1.5] max-[767px]:mb-5 max-[767px]:h-8 max-[767px]:w-8" viewBox="0 0 24 24" aria-hidden="true"><rect x="4" y="3" width="16" height="18" rx="1"/><path d="M8 7h8M8 11h8M8 15h5"/></svg><x-display-heading tag="h3" class="mb-4 text-[clamp(2rem,3.5vw,3rem)] max-[767px]:mb-3">Then build the card.</x-display-heading><p class="text-[1.125rem] leading-[1.75] max-[767px]:text-base max-[767px]:leading-[1.6]">Book competitors, choose match types and assign officials before the show begins.</p><p class="mt-6 text-sm font-bold max-[767px]:mt-4">Competitors / Match types / Officials</p></div>
        </div>
    </x-page-width>
</section>
